@PopulationApi_HostAddress = http://localhost:5045

###
# Obtener todos los países guardados
GET {{PopulationApi_HostAddress}}/api/v1/data/country
Accept: application/json

###
# Guardar países desde la API externa
POST {{PopulationApi_HostAddress}}/api/v1/data/country
Accept: application/json
